

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/IAAC/aws/kubernetes'
    backendServiceAWS: 'aws-for-terraform'
    backendAWSBucketName: 'codegenitor-terraform-backend-state-aws'
    backendAWSKey: 'kubernetes-dev.tfstate'
    
- task: TerraformTaskV4@4
  displayName: 'Terraform apply'
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '(System.DefaultWorkingDirectory)/IAAC/aws/kubernetes/main.tf'
    environmentServiceNameAWS: 'aws-for-terraform'





# terraform init
# terraform apply