

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

 # terraform init 
- task: TerraformTaskV4@4
  displayName: 'Terraform Init' 
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/IAAC/aws/kubernetes'
    backendServiceAWS: 'aws-for-terraform'
    backendAWSBucketName: 'codegenitor-terraform-backend-state-aws'
    backendAWSKey: 'kubernetes-dev.tfstate'

- task: TerraformTaskV4@4
  displayName: 'Terraform Apply' 
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'aws-for-terraform'
  
  

