trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo "Running k8s Terraform script"
    displayName: 'Run one-line script'

  - task: DownloadSecureFile@1
    name: publickey
    inputs:
      secureFile: 'azure_rsa.pub'
  
  - task: TerraformCLI@0
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/IAAC/azure/kubernetes'
      commandOptions: '-var client_id = $(client_id) -var client_secret = $(client_secret) -var ssh_public_key = $(publickey)'
      backendType: 'azurerm'
      backendServiceArm: 'Azure subscription 1(c4b5b6eb-ba85-4066-875e-fda817282325)'
      backendAzureRmSubscriptionId: 'c4b5b6eb-ba85-4066-875e-fda817282325'
      ensureBackend: true
      backendAzureRmResourceGroupName: 'terraform-backend-rg'
      backendAzureRmResourceGroupLocation: 'westeurope'
      backendAzureRmStorageAccountName: 'storagerichpong'
      backendAzureRmContainerName: 'storagerichpongcontainer'
      backendAzureRmKey: 'kubernetes-dev.tfstate'
      allowTelemetryCollection: true