trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo "Running k8s Terraform script"
    displayName: 'Run one-line script'
  - task: DownloadSecureFile@1
    name: publickey
    inputs:
      secureFile: 'azure_rsa.pub'

  - task: AzureCLI@2
    displayName: 'Azure Login'
    inputs:
      azureSubscription: 'c4b5b6eb-ba85-4066-875e-fda817282325'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az login --service-principal --tenant e98b7f57-deb3-4cc3-ab63-807439e6cfe7 --username codegenitor --password DORIRA123@1

  - task: TerraformCLI@0
    displayName: 'Initialize Terraform'
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/IAAC/azure/kubernetes'
      commandOptions: '-var client_id = $(client_id) -var client_secret = $client_secret) -var ssh_public_key = $(publickey.secureFilePath)'
      backendType: 'azurerm'
      ensureBackend: true
      backendAzureRmResourceGroupName: 'terraform-rsg'
      backendAzureRmResourceGroupLocation: 'westeurope'
      backendAzureRmStorageAccountName: 'storageaccontrichpong'
      backendAzureRmContainerName: 'storageaccontrichpongcontainer'
      backendAzureRmKey: 'kubernetes-dev.tfstate'
      allowTelemetryCollection: true
    continueOnError: true
