trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job: Firstjob
        steps:
          - bash: echo build Firstjob
          - bash: echo $(pipeline-variable)
          - bash: echo $(System.DefaultWorkingDirectory)
          - bash: echo $(Build.ArtifactStagingDirectory)
          - bash: node --version
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: |
                **/*yaml
                **/*tf
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
      - job: secondJob
        steps:
          - bash: echo build secondJob
  - stage: Devdeploy
    jobs:
      - job: Devdeploy
        steps:
          - bash: echo build Devdeploy
      - deployment: DevDeloymentJob
        environment: Dev
        strategy:
         runOnce:
           deploy:
             steps:
               - script: echo deploy to dev
  - stage: QAdeploy
    jobs:
      - job: QAdeploy
        steps:
          - bash: echo build QAdeploy
      - deployment: 
        environment: QA
        strategy:
         runOnce:
           deploy:
             steps:
               - script: echo deploy to QAdeploy
  - stage: ProdDeploy
    variables:
      environment: Dev
    dependsOn: 
    - Devdeploy
    - QAdeploy
    jobs:
      - job: ProdDeploy
        steps:
          - bash: echo build ProdDeploy
          - bash: echo $(environment)
