version: "3.8"
services:
  customer:
    build: ./customer
    container_name: customercontainer
    ports:
      - "3000:3000"
    volumes:
      - ./customer:/customer
      - customer/node_modules
    stdin_open: true
    tty: true
