trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo azure k8s Terraform azure cluster
    displayName: 'Run a one-line script'
  - task: DownloadSecureFile@1
    name: publickey
    inputs:
      secureFile: 'azure_rsa.pub'
  - task: TerraformCLI@0
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/IAAC/azure/kubernetes'
      commandOptions: '-var client_id=$(client_id) -var client_secrete=$(client_secrete) -var ssh_public_key=$(publickey.secureFilePath)'
      backendType: 'azurerm'
      backendServiceArm: 'azure-resource-management-connection'
      ensureBackend: true
      backendAzureRmResourceGroupName: 'terraform backend-rg'
      backendAzureRmResourceGroupLocation: 'westeurope'
      backendAzureRmStorageAccountName: 'codegenitorstorage-account'
      backendAzureRmContainerName: 'codegenitorcontainer'
      backendAzureRmKey: 'kubernetes-dev.tfstate'
      allowTelemetryCollection: true
